export const allowedTopics = [
  "Hello",
  "Hi",
  "SOX",
  "Sarbanes-Oxley",
  "Sarbanes-Oxley Act",
  "Sarbanes-Oxley Compliance",
  "Sarbanes-Oxley Audit",
  "Sarbanes-Oxley Controls",
  "Sarbanes-Oxley Testing",
  "Sarbanes-Oxley Requirements",
  "Sarbanes-Oxley Framework",
  "Sarbanes-Oxley Act",
  "Sarbanes-Oxley Compliance Requirements",
  "Sarbanes-Oxley Compliance Framework",
  "Sarbanes-Oxley Compliance Act",
  "Sarbanes-Oxley Compliance Testing",
  "Sarbanes-Oxley Compliance Controls",
  "Sarbanes-Oxley Compliance Audit",
  "Sarbanes-Oxley Compliance Act Requirements",
  "Sarbanes-Oxley Compliance Act Framework",
  "Sarbanes-Oxley Compliance Act Testing",
  "Sarbanes-Oxley Compliance Act Controls",
  "Sarbanes-Oxley Compliance Act Audit",
  "Sarbanes-Oxley Compliance Framework Requirements",
  "Sarbanes-Oxley Compliance Framework Testing",
  "Sarbanes-Oxley Compliance Framework Controls",
  "Sarbanes-Oxley Compliance Framework Audit",
  "Sarbanes-Oxley Compliance Testing Requirements",
  "Sarbanes-Oxley Compliance Testing Controls",
  "Sarbanes-Oxley Compliance Testing Audit",
  "Sarbanes-Oxley Compliance Controls Requirements",
  "Sarbanes-Oxley Compliance Controls Audit",
  "Sarbanes-Oxley Compliance Audit Requirements",
  "Sarbanes-Oxley CPRA",
  "Sarbanes-Oxley CPRA Compliance",
  "Sarbanes-Oxley CPRA Requirements",
  "Sarbanes-Oxley CPRA Framework",
  "Sarbanes-Oxley CPRA Act",
  "Sarbanes-Oxley CPRA Compliance Requirements",
  "Sarbanes-Oxley CPRA Compliance Framework",
  "Sarbanes-Oxley CPRA Compliance Act",
  "Sarbanes-Oxley CPRA Framework Requirements",
  "Sarbanes-Oxley CPRA Framework Act",
  "Sarbanes-Oxley CPRA Act Requirements",
  "Sarbanes-Oxley CPRA Compliance Requirements",
  "Sarbanes-Oxley CPRA Compliance Act Requirements",
  "Sarbanes-Oxley CPRA Compliance Framework Requirements",
  "Sarbanes-Oxley CPRA Compliance Act Framework",
  "Sarbanes-Oxley CPRA Compliance Framework Act",
  "Sarbanes-Oxley CPRA Compliance Testing",
  "Sarbanes-Oxley CPRA Compliance Controls",
  "Sarbanes-Oxley CPRA Compliance Audit",
  "Sarbanes-Oxley CPRA Compliance Testing Requirements",
  "Sarbanes-Oxley CPRA Compliance Testing Controls",
  "Sarbanes-Oxley CPRA Compliance Testing Audit",
  "Sarbanes-Oxley CPRA Compliance Controls Requirements",
  "Sarbanes-Oxley CPRA Compliance Controls Audit",
  "Sarbanes-Oxley CPRA Compliance Audit Requirements",
  "Sarbanes-Oxley CPRA Framework Requirements",
  "Sarbanes-Oxley CPRA Framework Act",
  "Sarbanes-Oxley CPRA Framework Testing",
  "Sarbanes-Oxley CPRA Framework Controls",
  "Sarbanes-Oxley CPRA Framework Audit",
  "Sarbanes-Oxley CPRA Act Requirements",
  "Sarbanes-Oxley CPRA Testing",
  "Sarbanes-Oxley CPRA Controls",
  "Sarbanes-Oxley CPRA Audit",
  "Sarbanes-Oxley CPRA Requirements",
  "Sarbanes-Oxley CPRA Act",
  "Sarbanes-Oxley CPRA Testing Requirements",
  "Sarbanes-Oxley CPRA Testing Controls",
  "Sarbanes-Oxley CPRA Testing Audit",
  "Sarbanes-Oxley CPRA Controls Requirements",
  "Sarbanes-Oxley CPRA Controls Audit",
  "Sarbanes-Oxley CPRA Audit Requirements",
  "Sarbanes-Oxley CPRA Act Requirements",
  "Sarbanes-Oxley CPRA Act Testing",
  "Sarbanes-Oxley CPRA Act Controls",
  "Sarbanes-Oxley CPRA Act Audit",
  "Sarbanes-Oxley CPRA Requirements",
  "Sarbanes-Oxley CPRA Testing",
  "Sarbanes-Oxley CPRA Controls",
  "Sarbanes-Oxley CPRA Audit",
  "Sarbanes-Oxley CPRA Requirements",
  "Sarbanes-Oxley CPRA Act",
  "Sarbanes-Oxley CPRA Testing Requirements",
  "Sarbanes-Oxley CPRA Testing Controls",
  "Sarbanes-Oxley CPRA Testing Audit",
  "Sarbanes-Oxley CPRA Controls Requirements",
  "Sarbanes-Oxley CPRA Controls Audit",
  "Sarbanes-Oxley CPRA Audit Requirements",
  "Sarbanes-Oxley CPRA Act Requirements",
  "Sarbanes-Oxley CPRA Act Testing",
  "Sarbanes-Oxley CPRA Act Controls",
  "Sarbanes-Oxley CPRA Act Audit",
  "Sarbanes-Oxley CPRA Requirements",
  "Sarbanes-Oxley CPRA Testing",
  "Sarbanes-Oxley SOD",
  "Sarbanes-Oxley Segregation of Duties",
  "Sarbanes-Oxley Segregation of Duties Requirements",
  "Sarbanes-Oxley Segregation of Duties Framework",
  "Sarbanes-Oxley Segregation of Duties Act",
  "Sarbanes-Oxley Segregation of Duties Compliance",
  "Sarbanes-Oxley Segregation of Duties Testing",
  "Sarbanes-Oxley Segregation of Duties Controls",
  "Sarbanes-Oxley Segregation of Duties Audit",
  "Sarbanes-Oxley Segregation of Duties Requirements",
  "Sarbanes-Oxley Segregation of Duties Framework Requirements",
  "Sarbanes-Oxley Segregation of Duties Act Requirements",
  "Sarbanes-Oxley Segregation of Duties Compliance Requirements",
  "Sarbanes-Oxley Segregation of Duties Testing Requirements",
  "Sarbanes-Oxley Segregation of Duties Controls Requirements",
  "Sarbanes-Oxley Segregation of Duties Audit Requirements",
  "Sarbanes-Oxley Segregation of Duties Framework Act",
  "Sarbanes-Oxley Segregation of Duties Framework Testing",
  "Sarbanes-Oxley Segregation of Duties Framework Controls",
  "Sarbanes-Oxley Segregation of Duties Framework Audit",
  "Sarbanes-Oxley Segregation of Duties Act Requirements",
  "Sarbanes-Oxley Segregation of Duties Act Testing",
  "Sarbanes-Oxley Segregation of Duties Act Controls",
  "Sarbanes-Oxley Segregation of Duties Act Audit",
  "Sarbanes-Oxley Segregation of Duties Compliance Requirements",
  "Sarbanes-Oxley Segregation of Duties Compliance Testing",
  "Sarbanes-Oxley Segregation of Duties Compliance Controls",
  "Sarbanes-Oxley Segregation of Duties Compliance Audit",
  "Sarbanes-Oxley Segregation of Duties Testing Requirements",
  "Sarbanes-Oxley Segregation of Duties Testing Controls",
  "Sarbanes-Oxley Segregation of Duties Testing Audit",
  "Sarbanes-Oxley Segregation of Duties Controls Requirements",
  "Sarbanes-Oxley Segregation of Duties Controls Audit",
  "Sarbanes-Oxley Segregation of Duties Audit Requirements",
  "Sarbanes-Oxley Segregation of Duties Framework Requirements",
  "Sarbanes-Oxley Segregation of Duties Framework Act",
  "Sarbanes-Oxley Segregation of Duties Framework Testing",
  "Sarbanes-Oxley Segregation of Duties Framework Controls",
  "Sarbanes-Oxley Segregation of Duties Framework Audit",
  "Sarbanes-Oxley Segregation of Duties Act Requirements",
  "Sarbanes-Oxley Segregation of Duties Act Testing",
  "Sarbanes-Oxley Segregation of Duties Act Controls",
  "Sarbanes-Oxley Segregation of Duties Act Audit",
  "Sarbanes-Oxley Segregation of Duties Compliance Requirements",
  "Sarbanes-Oxley Segregation of Duties Compliance Testing",
  "Sarbanes-Oxley Segregation of Duties Compliance Controls",
  "Sarbanes-Oxley Segregation of Duties Compliance Audit",
  "Sarbanes-Oxley Segregation of Duties Testing Requirements",
  "Sarbanes-Oxley Segregation of Duties Testing Controls",
  "Sarbanes-Oxley Segregation of Duties Testing Audit",
  "Sarbanes-Oxley Segregation of Duties Controls Requirements",
  "Sarbanes-Oxley Segregation of Duties Controls Audit",
  "Sarbanes-Oxley Segregation of Duties Audit Requirements",
  "Sarbanes-Oxley Segregation of Duties Framework Requirements",
  "Sarbanes-Oxley Segregation of Duties Framework Act",
  "Sarbanes-Oxley Segregation of Duties Framework Testing",
  "Sarbanes-Oxley Segregation of Duties Framework Controls",
  "Sarbanes-Oxley Segregation of Duties Framework Audit",
  "Sarbanes-Oxley Segregation of Duties Act Requirements",
  "Sarbanes-Oxley Segregation of Duties Act Testing",
  "Sarbanes-Oxley Segregation of Duties Act Controls",
  "Sarbanes-Oxley Segregation of Duties Act Audit",
  "Sarbanes-Oxley Segregation of Duties Compliance Requirements",
  "Sarbanes-Oxley Segregation of Duties Compliance Testing",
  "Sarbanes-Oxley Segregation of Duties Compliance Controls",
  "Sarbanes-Oxley Segregation of Duties Compliance Audit",
  "Sarbanes-Oxley Segregation of Duties Testing Requirements",
  "Sarbanes-Oxley Segregation of Duties Testing Controls",
  "Sarbanes-Oxley Segregation of Duties Testing Audit",
  "Sarbanes-Oxley Segregation of Duties Controls Requirements",
  "Sarbanes-Oxley Segregation of Duties Controls Audit",
  "Sarbanes-Oxley Segregation of Duties Audit Requirements",
  "Sarbanes-Oxley Segregation of Duties Framework Requirements",
  "Sarbanes-Oxley Segregation of Duties Framework Act",
  "Sarbanes-Oxley Segregation of Duties Framework Testing",
  "Sarbanes-Oxley Segregation of Duties Framework Controls",
  "Sarbanes-Oxley Segregation of Duties Framework Audit",
  "Sarbanes-Oxley Segregation of Duties Act Requirements",
  "Sarbanes-Oxley Segregation of Duties Act Testing",
  "Sarbanes-Oxley Segregation of Duties Act Controls",
  "Sarbanes-Oxley Segregation of Duties Act Audit",
  "Sarbanes-Oxley Segregation of Duties Compliance Requirements",
  "Sarbanes-Oxley Segregation of Duties Compliance Testing",
  "Sarbanes-Oxley Segregation of Duties Compliance Controls",
  "Sarbanes-Oxley Segregation of Duties Compliance Audit",
  "Sarbanes-Oxley Segregation of Duties Testing Requirements",
  "Sarbanes-Oxley Segregation of Duties Testing Controls",
  "Sarbanes-Oxley Segregation of Duties Testing Audit",
  "Sarbanes-Oxley Segregation of Duties Controls Requirements",
  "Sarbanes-Oxley Segregation of Duties Controls Audit",
  "Sarbanes-Oxley Segregation of Duties Audit Requirements",
  "Sarbanes-Oxley Segregation of Duties Framework Requirements",
  "Sarbanes-Oxley Segregation of Duties Framework Act",
  "Sarbanes-Oxley Segregation of Duties Framework Testing",
  "Sarbanes-Oxley Segregation of Duties Framework Controls",
  "Sarbanes-Oxley Segregation of Duties Framework Audit",
  "sox",
  "sox compliance",
  "sox audit",
  "sox controls",
  "sox testing",
  "sox requirements",
  "sox framework",
  "sox act",
  "sox compliance requirements",
  "sox compliance framework",
  "sox compliance act",
  "sox compliance testing",
  "sox compliance controls",
  "sox compliance audit",
  "sox compliance act requirements",
  "sox compliance act framework",
  "sox compliance act testing",
  "sox compliance act controls",
  "sox compliance act audit",
  "sox compliance framework requirements",
  "sox compliance framework testing",
  "sox compliance framework controls",
  "sox compliance framework audit",
  "sox compliance testing requirements",
  "sox compliance testing controls",
  "sox compliance testing audit",
  "sox compliance controls requirements",
  "sox compliance controls audit",
  "sox compliance audit requirements",
  "sox cpra",
  "sox cpra compliance",
  "sox cpra requirements",
  "sox cpra framework",
  "sox cpra act",
  "sox cpra compliance requirements",
  "sox cpra compliance framework",
  "sox cpra compliance act",
  "sox cpra framework requirements",
  "sox cpra framework act",
  "sox cpra act requirements",
  "sox cpra compliance requirements",
  "sox cpra compliance act requirements",
  "sox cpra compliance framework requirements",
  "sox cpra compliance act framework",
  "sox cpra compliance framework act",
  "sox cpra compliance testing",
  "sox cpra compliance controls",
  "sox cpra compliance audit",
  "sox cpra compliance testing requirements",
  "sox cpra compliance testing controls",
  "sox cpra compliance testing audit",
  "sox cpra compliance controls requirements",
  "sox cpra compliance controls audit",
  "sox cpra compliance audit requirements",
  "sox cpra framework requirements",
  "sox cpra framework act",
  "sox cpra framework testing",
  "sox cpra framework controls",
  "sox cpra framework audit",
  "sox cpra act requirements",
  "sox cpra testing",
  "sox cpra controls",
  "sox cpra audit",
  "sox cpra requirements",
  "sox cpra act",
  "sox cpra testing requirements",
  "sox cpra testing controls",
  "sox cpra testing audit",
  "sox cpra controls requirements",
  "sox cpra controls audit",
  "sox cpra audit requirements",
  "sox cpra act requirements",
  "sox cpra act testing",
  "sox cpra act controls",
  "sox cpra act audit",
  "sox cpra requirements",
  "sox cpra testing",
  "sox cpra controls",
  "sox cpra audit",
  "sox cpra requirements",
  "sox cpra act",
  "sox cpra testing requirements",
  "sox cpra testing controls",
  "sox cpra testing audit",
  "sox cpra controls requirements",
  "sox cpra controls audit",
  "sox cpra audit requirements",
  "sox cpra act requirements",
  "sox cpra act testing",
  "sox cpra act controls",
  "sox cpra act audit",
  "sox cpra requirements",
  "sox cpra testing",
  "sox sod",
  "sox segregation of duties",
  "sox segregation of duties requirements",
  "sox segregation of duties framework",
  "sox segregation of duties act",
  "sox segregation of duties compliance",
  "sox segregation of duties testing",
  "sox segregation of duties controls",
  "sox segregation of duties audit",
  "sox segregation of duties requirements",
  "sox segregation of duties framework requirements",
  "sox segregation of duties act requirements",
  "sox segregation of duties compliance requirements",
  "sox segregation of duties testing requirements",
  "sox segregation of duties controls requirements",
  "sox segregation of duties audit requirements",
  "sox segregation of duties framework act",
  "sox segregation of duties framework testing",
  "sox segregation of duties framework controls",
  "sox segregation of duties framework audit",
  "sox segregation of duties act requirements",
  "sox segregation of duties act testing",
  "sox segregation of duties act controls",
  "sox segregation of duties act audit",
  "sox segregation of duties compliance requirements",
  "sox segregation of duties compliance testing",
  "sox segregation of duties compliance controls",
  "sox segregation of duties compliance audit",
  "sox segregation of duties testing requirements",
  "sox segregation of duties testing controls",
  "sox segregation of duties testing audit",
  "sox segregation of duties controls requirements",
  "sox segregation of duties controls audit",
  "sox segregation of duties audit requirements",
  "sox segregation of duties framework requirements",
  "sox segregation of duties framework act",
  "sox segregation of duties framework testing",
  "sox segregation of duties framework controls",
  "sox segregation of duties framework audit",
  "sox segregation of duties act requirements",
  "sox segregation of duties act testing",
  "sox segregation of duties act controls",
  "sox segregation of duties act audit",
  "sox segregation of duties compliance requirements",
  "sox segregation of duties compliance testing",
  "sox segregation of duties compliance controls",
  "sox segregation of duties compliance audit",
  "sox segregation of duties testing requirements",
  "sox segregation of duties testing controls",
  "sox segregation of duties testing audit",
  "sox segregation of duties controls requirements",
  "sox segregation of duties controls audit",
  "sox segregation of duties audit requirements",
  "sox segregation of duties framework requirements",
  "sox segregation of duties framework act",
  "sox segregation of duties framework testing",
  "sox segregation of duties framework controls",
  "sox segregation of duties framework audit",
];
